# Esplora config (for signet/mainnet)
# esplora = "https://blockstream.info/api"
# esplora = "https://mempool.space/signet/api"

# RPC config (for regtest)
rpc_url = "http://localhost:18443"
rpc_user = "user"
rpc_pass = "password"
rpc_wallet = "coins-aggregator"

spacechain = "spacechain_regtest.bin"
keyfile = "aggregator_sk.hex"
interval = 30
network = "regtest"
genesis_pk = "43878a2a65c154d604cbe7d974d5dad1c63ce4dc2a68f697c45a4a3ef9ab8a21"
genesis_balance = 1000000000000