[package]
name = "coins-subchain"
version = "0.1.0"
edition = "2024"

[dependencies]
bitcoin = { version = "0.32.6", features = ["serde", "rand", "rand-std"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
hex = "0.4"
clap = { version = "4", features = ["derive"] }
bincode = { version = "2.0.1", features = ["serde"] }
toml = "0.8"
reqwest = { version = "0.12", features = ["json", "rustls-tls"] }
async-trait = "0.1"
anyhow = "1"
tokio = { version = "1", features = ["rt", "macros"] }
esplora-client = { git = "https://github.com/BitVM/rust-esplora-client", branch = "master" }
bitcoincore-rpc = "0.19.0"

[[bin]]
name = "subchain-setup"
path = "src/main.rs" 

[dev-dependencies]
tempfile = "3" 
