# Indexer service configuration for mutinynet signet

# Subchain configuration for autonomous block discovery
subchain = ".data/mutinynet/subchains/subchain_mutinynet.bin"
wallet_name = "coins-indexer"

[database]
state_db = ".data/mutinynet/state.db"
indexer_db = ".data/mutinynet/indexer.db"

[bitcoin]
rpc_url = "http://168.119.139.152:38332"
rpc_user = "bitcoin"
rpc_pass = "8723nasd0932n"
network = "signet"

[server]
api_port = 8083
host = "0.0.0.0"

[genesis]
genesis_pk = "43878a2a65c154d604cbe7d974d5dad1c63ce4dc2a68f697c45a4a3ef9ab8a21"
genesis_balance = 1000000000000
