# Indexer service configuration for regtest

# Subchain configuration for autonomous block discovery
subchain = ".data/regtest/subchains/subchain_regtest.bin"
wallet_name = "coins-indexer"

[database]
state_db = ".data/regtest/state.db"
indexer_db = ".data/regtest/indexer.db"

[bitcoin]
rpc_url = "http://localhost:18443"
rpc_user = "user"
rpc_pass = "password"
network = "regtest"

[server]
api_port = 8083
host = "0.0.0.0"

[genesis]
genesis_pk = "d3cf876dc108c2d3a81c8716a91678d9851518685b04859b021a132ee7440603"
genesis_balance = 1000000000000
