//! Spacechain client implementation.
//!
//! This module provides a high-level wrapper around a Bitcoin Core JSON-RPC
//! connection that is able to
//!
//! 1. read a `Spacechain` descriptor from disk,
//! 2. read a fee-paying secret key from the configuration file,
//! 3. create / load two dedicated wallets (hot + watch-only),
//! 4. keep track of the client and spacechain UTXOs,
//! 5. publish blobs using [`crate::publish`],
//! 6. perform an initial block download (IBD) streaming historical blocks, and
//! 7. watch the chain tip and forward new blocks via a user supplied closure.
//!
//! The goal is **not** to expose every single RPC method.  Instead we offer the
//! small set of helpers required by the demo application.

use std::path::{Path, PathBuf};
use std::time::Duration;

use anyhow::{anyhow, Context, Result};
use bitcoin::{Address, Block, PrivateKey, Txid};
use bitcoin::secp256k1::SecretKey;
use bitcoincore_rpc::{Auth, Client as RpcClient, RpcApi};
use serde::Deserialize;
use tokio::task::JoinHandle;
use tokio::time::sleep;

use crate::{publish, Spacechain};

// -----------------------------------------------------------------------------
// Configuration
// -----------------------------------------------------------------------------

/// Default wallet name holding the client's own spendable coins.
fn default_hot_wallet() -> String {
    "coins-sc".to_string()
}

/// Default watch-only wallet name following the spacechain UTXO.
fn default_watch_wallet() -> String {
    "coins-sc-watch".to_string()
}

/// Client-side configuration parsed from a TOML file.
#[derive(Debug, Deserialize, Clone)]
pub struct ClientConfig {
    /// Path to the binary *spacechain* descriptor generated by `spacechain-setup`.
    pub spacechain_file: PathBuf,

    /// Fee-paying secret key encoded in Wallet-Import-Format (WIF).
    pub private_key_wif: String,

    /// JSON-RPC connection settings for Bitcoin Core.
    pub rpc_url: String,
    pub rpc_user: String,
    pub rpc_pass: String,

    /// Optional custom wallet names.
    #[serde(default = "default_hot_wallet")]
    pub wallet_name: String,
    #[serde(default = "default_watch_wallet")]
    pub watch_wallet_name: String,
}

// -----------------------------------------------------------------------------
// SpacechainClient
// -----------------------------------------------------------------------------

pub struct SpacechainClient {
    cfg: ClientConfig,
    rpc_base: RpcClient,   // base (no wallet) RPC connection
    spacechain: Spacechain,
    fee_sk: SecretKey,
}

impl SpacechainClient {
    // ---------------------------------------------------------------------
    // Construction helpers
    // ---------------------------------------------------------------------

    /// Instantiate the client from a parsed [`ClientConfig`].
    pub fn new(cfg: ClientConfig) -> Result<Self> {
        // ---- load spacechain descriptor ----
        let sc_bytes = std::fs::read(&cfg.spacechain_file)
            .with_context(|| format!("failed to read {}", cfg.spacechain_file.display()))?;
        let spacechain = Spacechain::decode(&sc_bytes)
            .ok_or_else(|| anyhow!("invalid spacechain blob"))?;

        // ---- parse private key ----
        let pk: PrivateKey = cfg.private_key_wif.parse()
            .with_context(|| "invalid WIF in private_key_wif")?;
        let fee_sk = pk.inner;

        // ---- connect to RPC (base, no wallet loaded) ----
        let auth = Auth::UserPass(cfg.rpc_user.clone(), cfg.rpc_pass.clone());
        let rpc_base = RpcClient::new(&cfg.rpc_url, auth.clone())
            .with_context(|| "failed to connect to Bitcoin Core RPC")?;

        // ---- ensure wallets ----
        ensure_wallet(&rpc_base, &cfg.wallet_name, /*disable_private_keys*/ false)?;
        ensure_wallet(&rpc_base, &cfg.watch_wallet_name, /*disable_private_keys*/ true)?;

        // Import the spacechain address into the watch-only wallet (ignore duplicates)
        let watch_rpc = wallet_rpc(&cfg, &cfg.watch_wallet_name)?;
        let sc_addr = Address::p2wpkh(&spacechain.pubkey, spacechain.network);
        let _ = watch_rpc.import_address(&sc_addr, Some("spacechain"), Some(false));

        Ok(Self { cfg, rpc_base, spacechain, fee_sk })
    }

    /// Convenience helper: read, parse, and instantiate from a TOML file.
    pub fn from_config_file(path: impl AsRef<Path>) -> Result<Self> {
        let content = std::fs::read_to_string(&path)
            .with_context(|| format!("reading config {}", path.as_ref().display()))?;
        let cfg: ClientConfig = toml::from_str(&content)
            .with_context(|| "parsing client config")?;
        Self::new(cfg)
    }

    // ---------------------------------------------------------------------
    // Publish
    // ---------------------------------------------------------------------

    /// Publish a `blob` by embedding it into the Taproot annex of a single
    /// transaction constructed via [`crate::publish::publish_blob`].  Returns
    /// the transaction id on success.
    pub fn publish_blob(&self, blob: &[u8], fee_rate_sat_per_vb: u64) -> Result<Txid> {
        // Use the **last** anchor transaction so that the anchor we spend is
        // currently unspent.
        let anchor_txs = self.spacechain.reconstruct_txs();
        // Find the latest anchor whose zero-sat output (vout 1) is still unspent
        let mut last_anchor = None;
        for tx in anchor_txs.iter().rev() { // newest → oldest
            let out = bitcoin::OutPoint::new(tx.compute_txid(), 1);
            if self.rpc_base.get_tx_out(&out.txid, out.vout, Some(true))?.is_some() {
                last_anchor = Some(tx);
                break;
            }
        }
        let last_anchor = last_anchor.ok_or_else(|| anyhow!("no unspent anchor found"))?;

        // Select a fee-paying UTXO from the hot wallet (must be spendable).
        let hot_rpc = wallet_rpc(&self.cfg, &self.cfg.wallet_name)?;
        let utxos = hot_rpc.list_unspent(None, None, None, None, None)?;
        let fee_utxo = utxos.into_iter()
            .find(|u| u.spendable)
            .ok_or_else(|| anyhow!("no spendable utxo in hot wallet"))?;
        let fee_outpoint = bitcoin::OutPoint::new(fee_utxo.txid, fee_utxo.vout);

        let (anchor_out, publish_tx) = publish::publish_blob(
            blob,
            last_anchor,
            fee_outpoint,
            fee_utxo.amount.to_sat(),
            &self.fee_sk,
            fee_rate_sat_per_vb,
            self.spacechain.network,
        ).map_err(|e| anyhow!(e))?;
        // Silence unused variable warning (anchor_out may be used by caller in the future)
        let _ = anchor_out;

        // ----------------------------------------------------------------
        // Broadcast as a package (anchor + publish) using submitpackage RPC
        // ----------------------------------------------------------------
        use bitcoin::consensus::encode::serialize;
        use serde_json::json;

        // Raw-hex list: anchor (last_anchor) first, then publish_tx
        let hexes = vec![
            hex::encode(serialize(last_anchor)),
            hex::encode(serialize(&publish_tx)),
        ];

        // Call submitpackage; ignore detailed return value – any error will bubble
        hot_rpc.call::<serde_json::Value>("submitpackage", &[json!(hexes)])?;

        Ok(publish_tx.compute_txid())
    }

    // ---------------------------------------------------------------------
    // Block processing helpers
    // ---------------------------------------------------------------------

    /// Run an *initial block download* streaming every historical block to the
    /// supplied `callback` (oldest to newest).
    pub fn initial_block_download<F>(&self, mut callback: F) -> Result<()>
    where
        F: FnMut(Block) -> Result<()>,
    {
        let best_height = self.rpc_base.get_block_count()?;
        for height in 0..=best_height {
            let hash = self.rpc_base.get_block_hash(height)?;
            let block = self.rpc_base.get_block(&hash)?;
            callback(block)?;
        }
        Ok(())
    }

    /// Spawn a background task that polls for new blocks every `interval` and
    /// calls the `callback` for each newly tip block.
    pub fn start_block_watcher<F>(&self, interval: Duration, mut callback: F) -> JoinHandle<Result<()>>
    where
        F: FnMut(Block) -> Result<()> + Send + 'static,
    {
        // Capture copies for the async task
        let rpc_url  = self.cfg.rpc_url.clone();
        let rpc_user = self.cfg.rpc_user.clone();
        let rpc_pass = self.cfg.rpc_pass.clone();
        tokio::spawn(async move {
            let auth = Auth::UserPass(rpc_user, rpc_pass);
            let rpc = RpcClient::new(&rpc_url, auth)?;
            let mut last_height = rpc.get_block_count()?;
            loop {
                sleep(interval).await;
                let best = rpc.get_block_count()?;
                while last_height < best {
                    last_height += 1;
                    let hash = rpc.get_block_hash(last_height)?;
                    let block = rpc.get_block(&hash)?;
                    callback(block)?;
                }
            }
        })
    }
}

// -----------------------------------------------------------------------------
// Convenience helpers (private)
// -----------------------------------------------------------------------------

/// Build a *wallet-scoped* RPC handle (appends `/wallet/<name>` to the base URL).
fn wallet_rpc(cfg: &ClientConfig, wallet_name: &str) -> Result<RpcClient> {
    let url = format!("{}/wallet/{}", cfg.rpc_url.trim_end_matches('/'), wallet_name);
    let auth = Auth::UserPass(cfg.rpc_user.clone(), cfg.rpc_pass.clone());
    Ok(RpcClient::new(&url, auth)?)
}

/// Ensure that a wallet with `name` exists.  Creates or loads the wallet if necessary.
fn ensure_wallet(rpc: &RpcClient, name: &str, disable_private_keys: bool) -> Result<()> {
    // Already loaded?
    if rpc.list_wallets()?.iter().any(|w| w == name) {
        return Ok(());
    }
    // Try to load if it exists but isn't loaded.
    if rpc.load_wallet(name).is_ok() {
        return Ok(());
    }
    // Otherwise create a fresh wallet.
    rpc.create_wallet(name, Some(disable_private_keys), None, None, None)?;
    Ok(())
}
